In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
osaka = pd.read_csv('osaka_tripadvisor.csv')
osaka.head()

,name,address,rankingPosition,rawRanking,priceLevel,numberOfReviews,priceRange,description,cuisines/0,cuisines/1,cuisines/2,cuisines/3,cuisines/4,cuisines/5,cuisines/6,cuisines/7
0,Yakumido,"2-2-10 Haginochaya, Nishinari-Ku, Osaka 557-00...",1,4.779569,$,173,"$500 - $1,000","Please check out the schedule on google map, t...",Japanese,Asian,Vegetarian Friendly,Vegan Options,Gluten Free Options,NaN,NaN,NaN
1,Hokuto GEMS Namba,"3-7-19 Gems Namba 7F, Namba, Chuo, Osaka 539-0...",1,4.732521,$$ - $$$,539,"$1,000 - $4,000",《 すき焼きの美味さは肉で決まる！日本のごちそう「すきやき」をもっと身近に！！ 》 黒毛和牛...,Japanese,Asian,Grill,NaN,NaN,NaN,NaN,NaN
2,Okonomiyaki Chitose,"1-11-10 Taishi, Nishinari-ku, Osaka 557-0002 O...",7,4.701214,$,559,NaN,RE-OPEN NOW 1 NOVEMBER START 12：00～15：30 17：00...,Japanese,Asian,Vegetarian Friendly,NaN,NaN,NaN,NaN,NaN
3,Gyukatsu Motomura Namba,"3-3-1 Sugata Bldg B1F, Namba, Chuo, Osaka 542-...",2,4.693217,$$ - $$$,392,"$1,000 - $3,000",[Gyukatsu-MOTOMURA ] will continue to provide ...,Steakhouse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dotonbori Riverside Grill Wonder,"1-1-6 Riverside B1F, Dotombori, Chuo, Osaka 54...",2,4.113554,$$ - $$$,69,"$1,000 - $3,000",place you can communicate with local japanes! ...,Bar,Pub,American,International,Grill,NaN,NaN,NaN